app = "realbot-trench"  # <-- remplace par le nom exact de ton app si différent
primary_region = "cdg"  # Paris (ou la région que tu as choisie)

[env]
  PORT = "3000"
  CMD_PREFIX = "!"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Check TCP plutôt que HTTP GET (ton webhook accepte des POST)
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
